In [5]:
#Problem 1



In [ ]:
import numpy as np

In [37]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [38]:
y=5
np.column_stack([a**(y-1-i) for i in range(y)])

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]], dtype=int32)

In [39]:
np.vander(a, y,False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [ ]:
#Problem 2

In [40]:

import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [34]:
#b = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
#c = np.cumsum(b)
#n= 3
#d = c[:-3]
#e = c[3:]
#f = c[3:] - c[:-3]
#e,d,f,f[3:],f[2:]/3




(array([ 17,  25,  35,  46, 111, 183, 264, 363, 463, 613], dtype=int32),
 array([  3,   8,  15,  17,  25,  35,  46, 111, 183, 264], dtype=int32),
 array([ 14,  17,  20,  29,  86, 148, 218, 252, 280, 349], dtype=int32),
 array([ 29,  86, 148, 218, 252, 280, 349], dtype=int32),
 array([  6.66666667,   9.66666667,  28.66666667,  49.33333333,
         72.66666667,  84.        ,  93.33333333, 116.33333333]))